/** @type {import('tailwindcss').Config} */
export default {
    content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
    darkMode: "class",
    theme: {
        extend: {
            // fonts
            fontFamily: {
                heading: ["Pirata One", "serif"],
                content: ["Hack", "monospace"],
                code: ["Hack", "monospace"],
                paragraph: ["EB Garamond", "serif"],
            },
            // colors
            colors: {
                background: "hsl(var(--background))",
                foreground: "hsl(var(--foreground))",
                border: "hsl(var(--border))",
                primary: {
                    50: "hsl(var(--primary-50))",
                    100: "hsl(var(--primary-100))",
                    200: "hsl(var(--primary-200))",
                    300: "hsl(var(--primary-300))",
                    400: "hsl(var(--primary-400))",
                    500: "hsl(var(--primary-500))",
                    600: "hsl(var(--primary-600))",
                    700: "hsl(var(--primary-700))",
                    800: "hsl(var(--primary-800))",
                    900: "hsl(var(--primary-900))",
                    950: "hsl(var(--primary-950))",
                },
                secondary: {
                    50: "hsl(var(--secondary-50))",
                    100: "hsl(var(--secondary-100))",
                    200: "hsl(var(--secondary-200))",
                    300: "hsl(var(--secondary-300))",
                    400: "hsl(var(--secondary-400))",
                    500: "hsl(var(--secondary-500))",
                    600: "hsl(var(--secondary-600))",
                    700: "hsl(var(--secondary-700))",
                    800: "hsl(var(--secondary-800))",
                    900: "hsl(var(--secondary-900))",
                    950: "hsl(var(--secondary-950))",
                },
                info: {
                    50: "hsl(var(--info-50))",
                    100: "hsl(var(--info-100))",
                    200: "hsl(var(--info-200))",
                    300: "hsl(var(--info-300))",
                    400: "hsl(var(--info-400))",
                    500: "hsl(var(--info-500))",
                    600: "hsl(var(--info-600))",
                    700: "hsl(var(--info-700))",
                    800: "hsl(var(--info-800))",
                    900: "hsl(var(--info-900))",
                    950: "hsl(var(--info-950))",
                },
                success: {
                    50: "hsl(var(--success-50))",
                    100: "hsl(var(--success-100))",
                    200: "hsl(var(--success-200))",
                    300: "hsl(var(--success-300))",
                    400: "hsl(var(--success-400))",
                    500: "hsl(var(--success-500))",
                    600: "hsl(var(--success-600))",
                    700: "hsl(var(--success-700))",
                    800: "hsl(var(--success-800))",
                    900: "hsl(var(--success-900))",
                    950: "hsl(var(--success-950))",
                },
                warning: {
                    50: "hsl(var(--warning-50))",
                    100: "hsl(var(--warning-100))",
                    200: "hsl(var(--warning-200))",
                    300: "hsl(var(--warning-300))",
                    400: "hsl(var(--warning-400))",
                    500: "hsl(var(--warning-500))",
                    600: "hsl(var(--warning-600))",
                    700: "hsl(var(--warning-700))",
                    800: "hsl(var(--warning-800))",
                    900: "hsl(var(--warning-900))",
                    950: "hsl(var(--warning-950))",
                },
                danger: {
                    50: "hsl(var(--danger-50))",
                    100: "hsl(var(--danger-100))",
                    200: "hsl(var(--danger-200))",
                    300: "hsl(var(--danger-300))",
                    400: "hsl(var(--danger-400))",
                    500: "hsl(var(--danger-500))",
                    600: "hsl(var(--danger-600))",
                    700: "hsl(var(--danger-700))",
                    800: "hsl(var(--danger-800))",
                    900: "hsl(var(--danger-900))",
                    950: "hsl(var(--danger-950))",
                },
            },
            backgroundImage: {
                "hero-pattern": "url('/img/hero-pattern.svg')",
                "footer-texture": "url('/img/footer-texture.png')",
                "dots-foreground":
                    "radial-gradient(circle,hsl(var(--foreground)) 1px,transparent 1px)",
                "dots-background":
                    "radial-gradient(circle,hsl(var(--background)) 1px,transparent 1px)",
                "dots-primary":
                    "radial-gradient(circle,hsl(var(--primary-500)) 1px,transparent 1px)",
                "dots-secondary":
                    "radial-gradient(circle,hsl(var(--secondary-500)) 1px,transparent 1px)",
            },
        },
    },
    plugins: [],
};
