name: Build and upload to Vercel

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - master

jobs:
  build:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get -y install podman
          # sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common

      - name: Run build.sh
        run: bash build.sh

      - name: Copy contents of "dist/" into ".vercel/output/static/"
        run: mkdir -p .vercel/output/static/ && cp -r dist/** .vercel/output/static

      - name: Copy vercel-config.json to ".vercel/output/config.json"
        run: cp vercel-config.json .vercel/output/config.json

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
